#!/usr/bin/env python
from socketIO_client import SocketIO, LoggingNamespace
data = '00000000'
left = '0'
right = '0'
forward = '0'
backward = '0'
cClockwise = '0'
clockwise = '0'
up = '0'
down = '0'


def on_drone_server_response(*args):
	global data
	data = args
	
def keymapper(args):
	global left
	left = keymap[0]
	global right
	right = keymap[1]
	global forward
	forward = keymap[2]
	global backward
	backward = keymap[3]
	global cClockwise
	cClockwise = keymap[4]
	global clockwise
	clockwise = keymap[5]
	global up
	up = keymap[6]
	global down
	down = keymap[7]
	

socketIO = SocketIO('http://avela.ddns.net', 3000, LoggingNamespace)
socketIO.emit('DRONErequest', 'boot')
socketIO.on('IOanswer', on_drone_server_response)
socketIO.wait(seconds=1)
while True:
	
	socketIO.emit('DRONErequest', 'request data')
	socketIO.on('IOanswer', on_drone_server_response)
	socketIO.wait(seconds=0.1)
	print(data)
	keymap = data[0]
	keymapper(keymap)
	print('DIR: ' , left , right , forward , backward , 'ROT: ' , cClockwise , clockwise ,'ALT: ', up , down)
